### Normaliztion

In [1]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler,StandardScaler

In [2]:
x=np.array([[10],[20],[30],[40],[100]])
scaler=StandardScaler()
X_transformed=scaler.fit_transform(x)
print(X_transformed)

[[-0.9486833 ]
 [-0.63245553]
 [-0.31622777]
 [ 0.        ]
 [ 1.8973666 ]]

In [3]:
x=np.array([[10],[20],[30],[40],[100]])
scaler=MinMaxScaler(feature_range=(0,1))
X_transformed=scaler.fit_transform(x)
print(X_transformed)

[[0.        ]
 [0.11111111]
 [0.22222222]
 [0.33333333]
 [1.        ]]

In [4]:
x=np.array([[10],[20],[30],[40],[100]])
j=len(str(np.max(np.abs(x))))
X_transformed=x/10**j
print(X_transformed)

[[0.01]
 [0.02]
 [0.03]
 [0.04]
 [0.1 ]]

In [5]:
x=np.array([[10],[20],[30],[40],[100]])
j=len(str(np.max(np.abs(x))))
X_transformed=x/10**j
print(X_transformed)

[[0.01]
 [0.02]
 [0.03]
 [0.04]
 [0.1 ]]

### Feature Encoding Types
- nominal: no order  
- ordinal: defined order

In [6]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
cities=['Kathmandu','Pokhara','Biratnagar']
encoded=le.fit_transform(cities)
print(encoded)

[1 2 0]

In [ ]:

from sklearn.preprocessing import OrdinalEncoder
encoder=OrdinalEncoder(categories=[['poor','fair','good']])# 1row 3 column
quality=[['poor'],['fair'],['good']]#2d array (list of list) 3 row 1 column
encoded=encoder.fit_transform(quality)
print(encoded)

[[0.]
 [1.]
 [2.]]

In [8]:
import pandas as pd
df=pd.DataFrame({'source':['river','lake','well']})
df_encoded=pd.get_dummies(df,columns=['source'])
print(df_encoded)

   source_lake  source_river  source_well
0        False          True        False
1         True         False        False
2        False         False         True

In [9]:
import numpy as np
import time
x=np.random.random(10000000)
print(x[:5])
start=time.time()
for i in range(x.shape[0]):
  x[i]=x[i]+2
end=time.time()
print(x[:5])
print(f'Time taken is {end-start} seconds')

[0.59197418 0.84892753 0.24773406 0.1315178  0.5058998 ]
[2.59197418 2.84892753 2.24773406 2.1315178  2.5058998 ]
Time taken is 1.7566587924957275 seconds

In [10]:
import numpy as np
import time
x=np.random.random(10000000)
print(x[:5])
start=time.time()
x=x+2
end=time.time()
print(x[:5])
print(f'Time taken is {end-start} seconds')

[0.26732181 0.10499845 0.46742304 0.74235206 0.5465243 ]
[2.26732181 2.10499845 2.46742304 2.74235206 2.5465243 ]
Time taken is 0.0206756591796875 seconds

In [1]:
import pandas as pd
df=pd.read_csv("clean.csv")

In [2]:
df.head()

,PassengerId,Survived,Pclass,Name,Gender,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,C23 C25 C27,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,C23 C25 C27,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,C23 C25 C27,S

In [3]:
df.isna().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Gender         0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

In [4]:
df.shape

(1206, 12)

In [5]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,1206.00000,1206.000000,1206.000000,1206.000000,1206.000000,1206.000000,1206.000000
mean,655.94942,0.375622,2.309287,29.759912,0.345771,0.253731,25.606211
std,378.04858,0.484484,0.823733,12.082480,0.607569,0.564774,29.522289
min,1.00000,0.000000,1.000000,0.170000,0.000000,0.000000,0.000000
25%,331.25000,0.000000,2.000000,23.000000,0.000000,0.000000,7.895800
50%,649.50000,0.000000,3.000000,29.881138,0.000000,0.000000,13.000000
75%,984.75000,1.000000,3.000000,34.875000,1.000000,0.000000,26.550000
max,1309.00000,1.000000,3.000000,66.000000,3.000000,2.000000,164.866700